server:
  port: 80

---

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security_test
    username: root
    password: 1111

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

---
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 328258243485-b2h1bp5ah43m8rs7emecfe5d79gkoghm.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          naver:
            clientId: BRPo_jvYvoOGV9oyuoGZ
            clientSecret: H0jhRU25SC
            scope:
              - name
              - email
            clientName: Naver
            authorizationGrantType: authorization_code
            redirectUri: http://localhost/login/oauth2/code/naver

          kakao:
            clientId: 3262231b30f3665fc7c6aa27f90e4a39
            clientSecret: ji9eEtc6hlnTh1AzYBY22PkH2iynYeCA
            redirectUri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            client-name: Kakao
            scope:
                - profile_nickname
                - account_email

        provider:
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response

          kakao:
            authorization_uri: https://kauth.kakao.com/oauth/authorize
            token_uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user_name_attribute: id